spring.application.name=jwtdemo
spring.datasource.url=jdbc:mysql://localhost:3306/trainingdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=sherni123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# File upload limits
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# Secret Key (Min 32 chars) & Expiration time (24 hours)
jwt.secret=9a4f2c8d3e1b7a6f5c4d3b2a1e0f9b8a7c6d5e4f3a2b1c0e9d8c7b6a5f4e3d2c
jwt.expiration=86400000
server.port=${PORT:8080}